package groundcrew 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Baggageclaim struct {

	/*Url - Descr: Baggageclaim server URL to advertise directly to the
TSA.

If not specified, either the `baggageclaim` link is
used.
 Default: <nil>
*/
	Url interface{} `yaml:"url,omitempty"`

	/*ForwardAddress - Descr: Baggageclaim server connection address to forward through SSH to the TSA.

If not specified, the Baggageclaim server address is registered directly.
 Default: <nil>
*/
	ForwardAddress interface{} `yaml:"forward_address,omitempty"`

}