package groundcrew 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Garden struct {

	/*Address - Descr: Garden server connection address to advertise directly to the TSA.

If not specified, either the `garden` link is used, or
the instance's address is advertised if the link is not
found.
 Default: <nil>
*/
	Address interface{} `yaml:"address,omitempty"`

	/*ForwardAddress - Descr: Garden server connection address to forward through SSH to the TSA.

If not specified, the Garden server address is registered directly.
 Default: <nil>
*/
	ForwardAddress interface{} `yaml:"forward_address,omitempty"`

}