package baggageclaim 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Baggageclaim struct {

	/*BindIp - Descr: IP address on which Baggageclaim should listen for HTTP traffic.
 Default: 0.0.0.0
*/
	BindIp interface{} `yaml:"bind_ip,omitempty"`

	/*BindPort - Descr: Port on which Baggageclaim should listen for HTTP traffic.
 Default: 7788
*/
	BindPort interface{} `yaml:"bind_port,omitempty"`

	/*Yeller - Descr: Environment name to specify for errors emitted to Yeller.
 Default: 
*/
	Yeller Yeller `yaml:"yeller,omitempty"`

}