package atc 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Retention struct {

	/*Container - Descr: The duration to keep a failed step's containers before expiring them.
 Default: 1h
*/
	Container Container `yaml:"container,omitempty"`

}