package atc 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Role struct {

	/*Password - Descr: Password to use when connecting.
 Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*Name - Descr: Name of role to connect with.
 Default: atc
*/
	Name interface{} `yaml:"name,omitempty"`

}