package generators

const (
	structTemplate = `package releasejobs
/*
* File Generated by enaml generator
*/
type {{.JobName}} struct {
{{ range $key, $value := .Elements }}
	{{ $value.ElementName }} {{ $value.ElementType }} ` + "`" + `yaml:"{{$value.ElementYamlName}},omitempty"` + "`" + `
{{ end }}
}`
)
