package blackbox 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Blackbox struct {

	/*Syslog - Descr: directory with subdirectories containing log files. log lines will be tagged with subdirectory name.
 Default: /var/vcap/sys/log
*/
	Syslog Syslog `yaml:"syslog,omitempty"`

}